version: "3.7"

services:
  client:
    container_name: react-graphql-blueprint
    build: './client'
    command: npm run start
    environment:
      - PORT=8080
      - NODE_ENV=development
      - API_PORT=3000
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${CLIENT_HOST_PORT}:8080
